spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mobile_phone_shop
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      type: trace
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
